$(document).ready(function(){
  //alert("hi")
  $("#lotus1").click(function(){
    	$("#text1").toggle();
    	});
      $("#lotus1").click(function(){
        	$("#text2").hide();
        	});
          $("#lotus1").click(function(){
            	$("#text3").hide();
            	});
              $("#lotus1").click(function(){
                	$("#text4").hide();
                	});
                  $("#lotus1").click(function(){
                    	$("#text5").hide();
                    	});
                      $("#lotus1").click(function(){
                        	$("#text6").hide();
                        	});
      $("#lotus2").click(function(){
          $("#text2").toggle();
          });
          $("#lotus2").click(function(){
            	$("#text1").hide();
            	});
              $("#lotus2").click(function(){
                	$("#text3").hide();
                	});
                  $("#lotus2").click(function(){
                    	$("#text4").hide();
                    	});
                      $("#lotus2").click(function(){
                        	$("#text5").hide();
                        	});
                          $("#lotus2").click(function(){
                            	$("#text6").hide();
                            	});
          $("#lotus3").click(function(){
              $("#text3").toggle();
              });
              $("#lotus3").click(function(){
                	$("#text2").hide();
                	});
                  $("#lotus3").click(function(){
                    	$("#text1").hide();
                    	});
                      $("#lotus3").click(function(){
                        	$("#text4").hide();
                        	});
                          $("#lotus3").click(function(){
                            	$("#text5").hide();
                            	});
                              $("#lotus3").click(function(){
                                	$("#text6").hide();
                                	});
              $("#lotus4").click(function(){
                  $("#text4").toggle();
                  });
                  $("#lotus4").click(function(){
                    	$("#text2").hide();
                    	});
                      $("#lotus4").click(function(){
                        	$("#text3").hide();
                        	});
                          $("#lotus4").click(function(){
                            	$("#text1").hide();
                            	});
                              $("#lotus4").click(function(){
                                	$("#text5").hide();
                                	});
                                  $("#lotus4").click(function(){
                                    	$("#text6").hide();
                                    	});
                  $("#lotus5").click(function(){
                      $("#text5").toggle();
                      });
                      $("#lotus5").click(function(){
                        	$("#text2").hide();
                        	});
                          $("#lotus5").click(function(){
                            	$("#text3").hide();
                            	});
                              $("#lotus5").click(function(){
                                	$("#text4").hide();
                                	});
                                  $("#lotus5").click(function(){
                                    	$("#text1").hide();
                                    	});
                                      $("#lotus5").click(function(){
                                        	$("#text6").hide();
                                        	});
                                      $("#me").click(function(){
                                          $("#text6").toggle();
                                          });
                                          $("#me").click(function(){
                                            	$("#text2").hide();
                                            	});
                                              $("#me").click(function(){
                                                	$("#text3").hide();
                                                	});
                                                  $("#me").click(function(){
                                                    	$("#text4").hide();
                                                    	});
                                                      $("#me").click(function(){
                                                        	$("#text1").hide();
                                                        	});
                                                          $("#me").click(function(){
                                                            	$("#text5").hide();
                                                            	});


})
